#!/usr/bin/env sh

MOONRISE_DIR=${MOONRISE_DIR:=$(readlink -f $(dirname $BASH_SOURCE)"/..")}

FIREFOX_LOCALE=${FIREFOX_LOCALE:="en-US"}
FIREFOX_VERSION=${FIREFOX_VERSION:="54.0a1"}
FIREFOX_PLATFORM=${FIREFOX_PLATFORM:="win64"}
FIREFOX_CHANNEL=${FIREFOX_CHANNEL:="nightly"}

FIREFOX_ZIP_FILENAME=${FIREFOX_ZIP_FILENAME:="firefox-54.0a1.en-US.win64.zip"}
FIREFOX_ZIP_DOWNLOAD_URL=${FIREFOX_ZIP_DOWNLOAD_URL:="https://archive.mozilla.org/pub/firefox/"$FIREFOX_CHANNEL"/latest-mozilla-central/"$FIREFOX_ZIP_FILENAME}

FIREFOX_TMP_DIR=${FIREFOX_TMP_DIR:=$MOONRISE_DIR"/tmp/firefox"}
FIREFOX_TMP_ZIP=${FIREFOX_TMP_ZIP:=$FIREFOX_TMP_DIR"/"$FIREFOX_ZIP_FILENAME}

FIREFOX_DIR=${FIREFOX_DIR:=$FIREFOX_DIR"/firefox"}
FIREFOX_BIN=${FIREFOX_BIN:="firefox.exe"}
FIREFOX_BAT=${FIREFOX_BAT:="firefox.bat"}
FIREFOX_EXE=${FIREFOX_EXE:=$FIREFOX_DIR"/"$FIREFOX_BIN}

rm -rf $FIREFOX_TMP_DIR $FIREFOX_DIR
mkdir -p $FIREFOX_TMP_DIR

echo "Downloading " $FIREFOX_ZIP_DOWNLOAD_URL " to " $FIREFOX_TMP_ZIP &&
  curl -C - -L --progress-bar $FIREFOX_ZIP_DOWNLOAD_URL -o $FIREFOX_TMP_ZIP && \
  echo "Extracting "$FIREFOX_TMP_ZIP && \
  unzip $FIREFOX_TMP_ZIP
